# version: '3.8'

services:
  # Общий MySQL 5.7 для всех сайтов
  db:
    image: mysql:5.7
    container_name: wp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wp_site1
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - wp_net

  # Nginx как обратный прокси
  nginx:
    image: nginx:alpine
    container_name: wp_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/conf/proxy_params:/etc/nginx/proxy_params
      - ./nginx/logs:/var/log/nginx
    networks:
      - wp_net

  # Сайт 1
  site1:
    image: wordpress:6.8.2-php8.3-apache
    container_name: wp_site1
    restart: always
    environment:
      APACHE_SERVER_NAME: localhost
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wp_site1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://site1.webserver.local');
        define('WP_SITEURL', 'http://site1.webserver.local');
    volumes:
      # 1. Монтируем ТОЛЬКО папку плагина (важно!)
      - /vagrant/sites/site1/wp-content/plugins/WpQuiz:/var/www/html/wp-content/plugins/WpQuiz
      # 2. Отдельно монтируем uploads (чтобы не терять медиафайлы)
      - site1_uploads:/var/www/html/wp-content/uploads
      # Монтируем конфиг
      - /vagrant/sites/site3/wp-config.php:/var/www/html/wp-config.php
    networks:
      - wp_net

  site2:
    image: wordpress:6.8.2-php8.3-apache
    container_name: wp_site2
    restart: always
    environment:
      APACHE_SERVER_NAME: localhost
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wp_site2
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://site2.webserver.local');
        define('WP_SITEURL', 'http://site2.webserver.local');
    volumes:
      - /vagrant/sites/site2/wp-content/plugins/WpQuiz:/var/www/html/wp-content/plugins/WpQuiz
      - site2_uploads:/var/www/html/wp-content/uploads
      - /vagrant/sites/site2/wp-config.php:/var/www/html/wp-config.php
    networks:
      - wp_net

  site3:
    image: wordpress:6.8.2-php8.3-apache
    container_name: wp_site3
    restart: always
    environment:
      APACHE_SERVER_NAME: localhost
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wp_site3
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://site3.webserver.local');
        define('WP_SITEURL', 'http://site3.webserver.local');
    volumes:
      - /vagrant/sites/site3/wp-content/plugins/WpQuiz:/var/www/html/wp-content/plugins/WpQuiz
      - site3_uploads:/var/www/html/wp-content/uploads
      - /vagrant/sites/site3/wp-config.php:/var/www/html/wp-config.php
    networks:
      - wp_net

volumes:
  db_data:
  site1_uploads:
  site2_uploads:
  site3_uploads:

networks:
  wp_net:
    driver: bridge
