CREATE DATABASE IF NOT EXISTS wp_site2;
CREATE DATABASE IF NOT EXISTS wp_site3;
GRANT ALL PRIVILEGES ON wp_site2.* TO 'wpuser'@'%';
GRANT ALL PRIVILEGES ON wp_site3.* TO 'wpuser'@'%';
FLUSH PRIVILEGES;